### PR TITLE
Updated the openapi specification

### PR DESCRIPTION
**Pull request by dumheter**
* Transaction had a get function, with data. That is not allowed, so I renamed them into new and info, both being POST operatinos.
* Changed return content for some functions, they now return a repsonse structure.
* Removed the response cases where they use the html codes, they seem to be reserved for the http software, not for the application.

### CODE REVIEW

**Comment by LionelJouin** [comment]
I would prefer the naming I set.
We have to keep the GET method for the method used to get info about transactions since we are requesting data, we are not sending data in order to save it in a database, or here in the blockchain.
[HTTP Request Methods](https://www.w3schools.com/tags/ref_httpmethods.asp)

The response structure would be interesting for the errors with a message explaining the reason

"the html codes", I guess you mean the http codes? I really think we should use these http response status codes. there are used in the application, it is easier to handle the request with these codes.

**Review by LionelJouin — CHANGES_REQUESTED** [review]
I would prefer the naming I defined.
We have to keep the GET method for the method used to get info about transactions since we are requesting data, we are not sending data in order to save it in a database, or here in the blockchain.
HTTP Request Methods

The response structure is a good idea, it would be interesting for the errors with a message explaining the reason.

"the html codes", I guess you mean the http codes? I really think we should use these http response status codes. there are used in the application, it is easier to handle the request with these codes.

**Comment by dumheter** [comment]
Regarding keeping the transaction/info as a GET request:

**Comment by dumheter** [comment]
Regarding keeping the names and sticking with the GET request. The package "rocket" I use as REST server does not support having a payload with the GET request. And in the [http specification](https://tools.ietf.org/html/rfc7231#section-4.3.1) it is stated:

" A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request."

So we can't keep the transaction GET request as you have defined it.

I read more about the http codes, sure lets keep it, putting them back in.

**Review by LionelJouin — CHANGES_REQUESTED** [review]
Yes, It's not possible to send data in the body of a GET request, we have to keep them the data a url parameters (Query Parameters).

**Comment by dumheter** [comment]
Oh I see, so it will be like
GET /transaction?ip=...?limit=...

I have a question though, what is the "skip" parameter for? I dont understand what this means "Useful for pagination".

**Comment by LionelJouin** [comment]
Yes, exactly.
Imagine you have 1000 transactions, and you set the limit to 10, so the api will return the 10 first transactions of the 1000 (range 0 - 9), if you set the skip to 10, you can consider you are in the page 2, so the api return the 10 next transactions (range 10 - 19).

**Comment by dumheter** [comment]
Okey, I have updated the spec file to what we agreed on, did I miss anything or something needs changing? @LionelJouin

**Review by LionelJouin — APPROVED** [review]
I think it's good.

**Pull request merged**
