### PR TITLE
Fixing specs of the api 

### PR DESCRIPTION
**Pull request by LionelJouin**
Fix boolean type, use response component

### CODE REVIEW

**Comment by dumheter** [comment]
rebased with master

**Comment by LionelJouin** [comment]
I'm not sure, What should I do?

**Comment by dumheter** [comment]
"rebase with master" was just my explaination for pushing with force ^^

I have implemented your changed to the REST server, and added another response thing to the get request. @LionelJouin could you look it over, and merge if it looks good?

**Review by LionelJouin — COMMENTED** [review]
Good

**Pull request merged**
